lang: zh-CN
url: https://bi1111.github.io/ruichenxu.github.io/
baseurl: ""
title: Ruichen Xu
subtitle: PhD Candidate / AI4Science Researcher
email: ruichen.xu@stonybrook.edu
permalink: pretty
markdown: kramdown
kramdown:
  input: GFM
  math_engine: mathjax
plugins: []
nav:
  - { title: "Home", url: "/" }
  - { title: "Bio", url: "/bio/" }
  - { title: "Group", url: "/group/" }
  - { title: "Topics", url: "/topics/" }
  - { title: "Papers", url: "/papers/" }
  - { title: "Prospective Students", url: "/prospective/" }
  - { title: "Courses", url: "/courses/" }
  - { title: "Recent", url: "/recent/" }
social:
  scholar: https://scholar.google.com/citations?user=IBXYwoQAAAAJ
  github: https://github.com/bi1111
  linkedin: https://www.linkedin.com/in/%E7%91%9E%E8%BE%B0-%E5%BE%90-b30b55197/
  openreview: https://openreview.net/profile?id=%7ERuichen_Xu2
collections:
  news:
    output: true
    permalink: /news/:name/
